/* SegaMap v2.2 — single stable search engine */
(function(){
  'use strict';
  var cache={}, timers={}, seq={};
  function esc(s){return String(s==null?'':s).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
  function area(item){var a=item.address||{};return a.suburb||a.neighbourhood||a.village||a.town||a.city||a.municipality||a.county||'Île Maurice';}
  function nameOf(item,q){var d=item.namedetails||{};return d['name:fr']||d.name||item.name||(item.display_name||q).split(',')[0]||q;}
  function local(q){try{return typeof searchNodes==='function'?(searchNodes(q)||[]):[];}catch(e){return [];}}
  function merge(a,b){var seen={},out=[];(a||[]).concat(b||[]).forEach(function(n){if(!n||seen[n.id])return;seen[n.id]=1;out.push(n);});return out.slice(0,20);}
  function add(items,out,q){(items||[]).forEach(function(item,i){var lat=Number(item.lat),lon=Number(item.lon);if(!isFinite(lat)||!isFinite(lon))return;var name=nameOf(item,q),id='geo22:'+encodeURIComponent(q.toLowerCase())+':'+i+':'+lat.toFixed(5)+':'+lon.toFixed(5);if(nodes[id]){out.push(nodes[id]);return;}if(typeof addNode!=='function')return;addNode(id,name,'poi',area(item),lat,lon);nodes[id].onlineSearch=true;nodes[id].osmType=item.type||'';nodes[id].osmClass=item.class||'';nodes[id].displayAddress=item.display_name||name;out.push(nodes[id]);if(typeof allNodesList!=='undefined'&&allNodesList.indexOf(nodes[id])===-1)allNodesList.push(nodes[id]);});}
  function online(q){var key=q.toLowerCase();if(cache[key])return Promise.resolve(cache[key]);var url='https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&namedetails=1&dedupe=1&limit=20&countrycodes=mu&bounded=1&viewbox=57.30,-19.65,57.90,-20.55&layer=address,poi,railway,natural,manmade&accept-language=fr,en&q='+encodeURIComponent(q);return fetch(url,{headers:{Accept:'application/json'}}).then(function(r){return r.ok?r.json():[];}).then(function(items){var out=[];add(items,out,q);cache[key]=out.slice(0,20);return cache[key];}).catch(function(){return [];});}
  function render(input,box,results){if(!results.length){box.innerHTML='<div class="sugg-item" style="cursor:default;color:#8b949e">Aucun résultat — appuyez sur Entrée pour chercher partout à Maurice</div>';box.classList.add('open');box.style.display='block';return;}box.innerHTML=results.map(function(n){return '<div class="sugg-item" data-sega-v22-id="'+esc(n.id)+'"><span class="sugg-name">'+esc(n.name)+'</span><span class="sugg-meta">'+esc(n.displayAddress||n.area||'Île Maurice')+'</span></div>';}).join('');box.classList.add('open');box.style.display='block';}
  function select(input,box,n){if(!n)return;input.value=n.name;input.dataset.selectedId=n.id;box.classList.remove('open');box.style.display='none';if(typeof homeMap!=='undefined'&&homeMap&&isFinite(n.lat)&&isFinite(n.lon))homeMap.setView([n.lat,n.lon],16);}
  function setup(id,boxId){var input=document.getElementById(id),box=document.getElementById(boxId);if(!input||!box)return;
    input.addEventListener('input',function(){var q=input.value.trim(),token=(seq[id]||0)+1;seq[id]=token;if(timers[id])clearTimeout(timers[id]);if(!q){box.classList.remove('open');box.innerHTML='';return;}timers[id]=setTimeout(function(){if(seq[id]!==token)return;render(input,box,local(q));},120);},true);
    input.addEventListener('keydown',function(e){if(e.key!=='Enter')return;var q=input.value.trim();if(q.length<2)return;e.preventDefault();var token=(seq[id]||0)+1;seq[id]=token;box.innerHTML='<div class="sugg-item" style="cursor:default;color:#8b949e">Recherche en cours…</div>';box.classList.add('open');box.style.display='block';online(q).then(function(results){if(seq[id]!==token||input.value.trim()!==q)return;render(input,box,merge(local(q),results));});},true);
    box.addEventListener('pointerdown',function(e){var item=e.target.closest('[data-sega-v22-id]');if(!item)return;e.preventDefault();e.stopPropagation();var n=nodes[item.getAttribute('data-sega-v22-id')];select(input,box,n);},true);
    input.addEventListener('focus',function(){if(input.value.trim()&&box.innerHTML.trim())box.classList.add('open');},true);
  }
  function style(){var s=document.createElement('style');s.textContent='#screen-home .fields-wrap{position:relative!important;z-index:3000!important}#screen-home .suggestions{position:absolute!important;left:0!important;right:0!important;top:calc(100% + 4px)!important;z-index:99999!important;display:none;max-height:42vh;overflow-y:auto!important;-webkit-overflow-scrolling:touch;pointer-events:auto!important;background:#fff!important;box-shadow:0 10px 28px rgba(0,0,0,.16);border-radius:14px}#screen-home .suggestions.open{display:block!important}#screen-home .sugg-item{position:relative!important;z-index:100000!important;pointer-events:auto!important;touch-action:manipulation!important}';document.head.appendChild(s);}
  function boot(){style();setup('origin-input','origin-sugg');setup('dest-input','dest-sugg');}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
